### ISSUE TITLE
自定义编辑器高度有问题

### ISSUE THREAD

**Issue by salamander-mh** [wangfupeng1988/wangEditor#1091]
我给container设置了高度，但是编辑器区域高度还是原来的

**Comment by wangfupeng1988** [comment]
看文档 https://www.kancloud.cn/wangfupeng/wangeditor3/335769 我在下面补充了设置高度的说明

**Comment by Xuhao** [comment]
@wangfupeng1988  
看到很多问告诉问题给提示去看这个demo，但我这里不能work，demo里说设置editor用的那个element的高度，但真实的高度是里面的`.w-e-text-container` 来控制的，而这个高度又是写死的300px。所以能不能在demo里更新下？

**Comment by Xuhao** [comment]
我这里的变通办法是
通过css控制：
```css
.w-e-text-container[style] {
  height: auto !important;
}
```

通过jQuery:
```javascript
...
editor.create();
$("div.w-e-text-container").css({ height: 'auto' });
```
