### ISSUE TITLE
IE设置H1自动加粗的问题

### ISSUE THREAD

**Issue by hdzakk** [wangfupeng1988/wangEditor#1373]
在IE浏览器中，当输入一段文字时然后对文字进行H1的操作，文字会自动的加粗了？这能解决吗？
![image](https://user-images.githubusercontent.com/11908815/37184845-612075b0-2378-11e8-9173-7d486ba91d62.png)

**Comment by wangfupeng1988** [comment]
`<h1>`本来就是具有加粗属性的，你要不让`<h1>`加粗，那么你可以为网页写一个统一的样式

```css
h1 {
    font-weight: normal;
}
```
