### ISSUE TITLE
样式与其它库冲突.

### ISSUE THREAD

**Issue by 390720046** [wangfupeng1988/wangEditor#401]
![default](https://cloud.githubusercontent.com/assets/8318747/18080997/6990ff94-6eca-11e6-95bc-862b952df699.png)

使用的是min的没有试过未压缩版的.发现不行去换了一个2016-08-06的压缩版就好了
配置:
``` javascript
var editor = new wangEditor('test');
editor.config.uploadImgUrl = '/admin/editor_upload';
editor.create();
```
好吧试了一下是因为easyui冲突了。。。不知道为什么又弄了一下又可以插入图片了，，但是还有个问题menu-item上的提示出不来了,还是跟easyui冲突。好吧找到问题所在了被其他组件的css样式覆盖了.menu-item这种class太常见了测试了一下easyui的css中有
``` css
.menu-item {
    overflow: hidden;
}
```
所以自己加一个css样式就好了
``` css
.menu-item {
    overflow: visible;
}
```
