### ISSUE TITLE
给 .wangEditor-container 添加 border-radius 样式

### ISSUE THREAD

**Issue by zhuscat** [wangfupeng1988/wangEditor#409]
<img width="127" alt="2016-09-07 9 25 23" src="https://cloud.githubusercontent.com/assets/14963619/18296579/37950a30-74dd-11e6-848e-34319feda7a3.png">

左上角和右上角会变成这个样子，有部分是白色的，左下角和右下角正常。

**Comment by zhangyd-c** [comment]
这是你自己的样式冲突问题....

**Comment by qtnote** [comment]
.wangEditor-container{
 overflow:hidden;
}

加上这个就可以了

**Comment by zhuscat** [comment]
@zhangyd-c @qtnote 好像只加上那个不行，我最近碰到一个类似的，我加上 `overflow: hidden;` 之后，还是不行，不清楚这里该怎么调：
不加 `overflow: hidden;`
![2016-09-09 9 38 30](https://cloud.githubusercontent.com/assets/14963619/18388875/ee122c1c-76d5-11e6-93fa-a0deb41c2ba3.png)
加了 `overflow: hidden;`
![2016-09-09 9 37 55](https://cloud.githubusercontent.com/assets/14963619/18388884/fa877d58-76d5-11e6-8e7e-0d5b3661bc9a.png)
给内部元素加上与外部元素同样的 `border-radius`
![2016-09-09 9 37 36](https://cloud.githubusercontent.com/assets/14963619/18388901/0e5c56f0-76d6-11e6-9f12-61b7434d3455.png)

以下是 `SCSS`

```scss
.zc-sub-menu-drop-down {
  width: 100%;
  border: 1px solid $border-gary-color;
  border-radius: 4px;
  position: absolute;
  left: 0;
  opacity: 0;
  // overflow: hidden;
  // box-shadow: $base-box-shadow;
  transform-origin: top;
  transition: $base-transition;
  transform: scaleY(0);

  &.zc-sub-menu-drop-down-open {
    opacity: 1;
    transform: scaleY(1);
  }

  .zc-menu-item-default {
    width: 100%;
    color: $primary-font-color;
    // border-radius: 4px;
    padding: 0;
    border-bottom: none;
  }

  .zc-menu-item-default:hover {
    background-color: $primary-color-light-lighter;
    color: $primary-color;
    border-bottom: none;
  }

  .zc-menu-item-default-active {
    background-color: #fff;
    color: $primary-color;
  }
}
```

`html` 结构：

```
.zc-sub-menu-drop-down
  .zc-menu-item-default
  .zc-menu-item-default
  .zc-menu-item-default
  .zc-menu-item-default
  .zc-menu-item-default
  .zc-menu-item-default
```
