### ISSUE TITLE
菜单栏无法自适应

### ISSUE THREAD

**Issue by IVANLEE99** [wangfupeng1988/wangEditor#732]
![image](https://cloud.githubusercontent.com/assets/18308725/26768686/3953fc3a-49dc-11e7-83fd-beab738190e7.png)
/cc /all

**Comment by IVANLEE99** [comment]
是用了flex的原因吗？

**Comment by wangfupeng1988** [comment]
是的。
我一直觉得编辑器的菜单栏中菜单换行之后不好看，因此v3版本直接禁止了，要不你增加宽度，要不你减少菜单。

**Comment by zuibunan** [comment]
```css
.w-e-toolbar {
    flex-wrap: wrap;
}
```
覆盖下样式即可，不过不知道会不会影响菜单选项的定位
